spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/reserve_open?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
