spring:
  datasource:
    url: jdbc:mysql://gpu-mysql:3306/reserve_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: gpu_monitor_7779
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: gpu-redis